[package]
name = "python-to-rust"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>", "E. Dunham <rustffi@edunham.net>"]
edition = "2018"

[lib]
name = "sum_up"
crate-type = ["dylib"]

